Write a function so that the columns of the output matrix are powers of the inputvector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

In [43]:
import numpy as np

def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx



inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")



The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:The moving average sequence has n-k+1 elements as shown below.The moving averages with k=4 of a ten-value sequence (n=10) is shown belowi1  2  3  4  5  6  7  8  9 10======= == == == == == == == == ==Input 10 20 30 40 50 60 70 80 90 100 y125 = (10+20+30+40)/4y235 = (20+30+40+50)/4y345 = (30+40+50+60)/4y455 = (40+50+60+70)/4y565 = (50+60+70+80)/4y675 = (60+70+80+90)/4y785 = (70+80+90+100)/4Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question:Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [48]:
def genrunningAvg(arr,window):

    for i in range(0,(arr.size-window+1)):
        
        numlist=arr[i:(i+window)]
        avg=sum(numlist)/window
        print("Elements in array ",numlist,"\t \tAverage",avg)
            

In [49]:
test1=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
genrunningAvg(test1,3)

Elements in array  [3 5 7] 	 	Average 5.0
Elements in array  [5 7 2] 	 	Average 4.666666666666667
Elements in array  [7 2 8] 	 	Average 5.666666666666667
Elements in array  [ 2  8 10] 	 	Average 6.666666666666667
Elements in array  [ 8 10 11] 	 	Average 9.666666666666666
Elements in array  [10 11 65] 	 	Average 28.666666666666668
Elements in array  [11 65 72] 	 	Average 49.333333333333336
Elements in array  [65 72 81] 	 	Average 72.66666666666667
Elements in array  [72 81 99] 	 	Average 84.0
Elements in array  [ 81  99 100] 	 	Average 93.33333333333333
Elements in array  [ 99 100 150] 	 	Average 116.33333333333333
